export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD"
export const SAVE_USER_INFO = "SAVE_USER_INFO"