export const GET_CLASSROOM_SUCCESS = "GET_CLASSROOM_SUCCESS";
export const GET_CLASSROOM_REQUEST = "GET_CLASSROOM_REQUEST";
export const GET_CLASSROOM_FAILURE = "GET_CLASSROOM_FAILURE";

export const CREATE_CLASSROOM_SUCCESS = "CREATE_CLASSROOM_SUCCESS";
export const CREATE_CLASSROOM_REQUEST = "CREATE_CLASSROOM_REQUEST";
export const CREATE_CLASSROOM_FAILURE = "CREATE_CLASSROOM_FAILURE";


