export const GET_HOTEL_SUCCESS = "GET_HOTEL_SUCCESS";
export const GET_HOTEL_REQUEST = "GET_HOTEL_REQUEST";
export const GET_HOTEL_FAILURE = "GET_HOTEL_FAILURE";

export const GET_HOTEL_FILTER_SUCCESS = "GET_HOTEL_FILTER_SUCCESS";
export const GET_HOTEL_FILTER_REQUEST = "GET_HOTEL_FILTER_REQUEST";
export const GET_HOTEL_FILTER_FAILURE = "GET_HOTEL_FILTER_FAILURE";

export const GET_DETAIL_HOTEL_REQUEST = "GET_DETAIL_HOTEL_REQUEST";
export const GET_DETAIL_HOTEL_SUCCESS = "GET_DETAIL_HOTEL_SUCCESS";
export const GET_DETAIL_HOTEL_FAILURE = "GET_DETAIL_HOTEL_FAILURE";

export const GET_ROOMS_HOTEL_REQUEST = "GET_ROOMS_HOTEL_REQUEST";
export const GET_ROOMS_HOTEL_SUCCESS = "GET_ROOMS_HOTEL_SUCCESS";
export const GET_ROOMS_HOTEL_FAILURE ="GET_ROOMS_HOTEL_FAILURE";

export const FILTER_HOTEL_BY_SORT = "FILTER_HOTEL_BY_SORT"

export const CREATE_REVIEW_FAILURE = "CREATE_REVIEW_FAILURE";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST"

export const SEARCH_HOTEL = "SEARCH_HOTEL";