export const GET_SITE_SUCCESS = "GET_SITE_SUCCESS";
export const GET_SITE_REQUEST = "GET_SITE_REQUEST";
export const GET_SITE_FAILURE = "GET_SITE_FAILURE";

export const GET_SITE_DETAIL_SUCCESS = "GET_SITE_DETAIL_SUCCESS"
export const GET_SITE_DETAIL_REQUEST = "GET_SITE_DETAIL_REQUEST"
export const GET_SITE_DETAIL_FAILURE = "GET_SITE_DETAIL_FAILURE"

export const GET_PLACE_SITE_SUCCESS = "GET_PLACE_SITE_SUCCESS"
export const GET_PLACE_SITE_REQUEST = "GET_PLACE_SITE_REQUEST"
export const GET_PLACE_SITE_FAILURE = "GET_PLACE_SITE_FAILURE"